name = "KnetLayers"
uuid = "e09e3f5a-3c2e-516c-a806-60ae64389a85"
authors = ["ekinakyurek <akyurekekin@gmail.com>"]
version = "0.1.0"

[deps]
AutoGrad = "6710c13c-97f1-543f-91c5-74e8f7d95b35"
Knet = "1902f260-5fb4-5aff-8c31-6271790ab950"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Printf", "Dates"]
