name = "KnetLayers"
uuid = "e09e3f5a-3c2e-516c-a806-60ae64389a85"
authors = ["ekinakyurek <akyurekekin@gmail.com>"]
version = "0.2.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
AutoGrad = "6710c13c-97f1-543f-91c5-74e8f7d95b35"
BytePairEncoding = "a4280ba5-8788-555a-8ca8-4a8c3d966a71"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
InternedStrings = "7d512f48-7fb1-5a58-b986-67e6dc259f01"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Knet = "1902f260-5fb4-5aff-8c31-6271790ab950"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
WordTokenizers = "796a5d58-b03d-544a-977e-18100b691f6e"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
Knet = "1.3.0"
julia = "1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Printf", "Test", "Dates"]
